services:
  db:
    image: postgres:14.10
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "ways"
      POSTGRES_PASSWORD: "83725"
    ports:
      - 5432:5432
  redis:
    image: redis:7.2.3
    ports:
      - 6379:6379