services:
  db:
    container_name: postgres
    image: postgres:14.10
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "ways"
      POSTGRES_PASSWORD: "83725"
    ports:
      - 5432:5432
    networks:
      - my-net
  redis:
    container_name: redis
    image: redis:7.2.3
    ports:
      - 6379:6379
    networks:
      - my-net
  app:
    container_name: backend
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    image: backend:latest
    networks:
      - my-net
    depends_on:
      - redis
      - db
networks:
  my-net:
    driver: bridge