spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: ways
    password: 83725
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
server:
  error:
    include-message: always